### ISSUE TITLE
Enhancement: Maximize "Account" field selector

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/SmartTemplate4#110]
![smarttemplate-3 3 setting-window](https://user-images.githubusercontent.com/26068595/103489674-5d824e80-4e16-11eb-8149-6e4160210e15.jpg)

To limit the ambiguity of choice in case of multiple identities... and need of resizing of 
"Setting" window.

In addition, **storing/restoring the last size and position of this window** would be really useful for complex configurations/testing associated with these multiple identities.

**Comment by RealRaven2000** [comment]
The underlying problem here is that this dialog has a lot of flex properties - and unfortunately it starts with the shortes possible string "common". but I hope I can fix that with some CSS - it's tricky. I was actually quite happy that I managed to make the edit fields expand vertically in 3.1 or 3.2 - but definitely this (maximize account dropdown horizontally) is on my wish list too.

There is actually one feature that worked in Thunderbird 68 which preselected your current account. I was lazy an didn't track that in its own issue, but it will also somewhat alleviate this issue as accounts usually have much longer names. So here is the new issue: #112 which will make the configuration a lot easier.

**Comment by RealRaven2000** [comment]
Not quite sure what I am doing _exactly_ here, but there is a trial version that seems to work maximizing the dropdown in Windows. Would be interesting to see whether it works on Mac, too:

[smartTemplate-fx-3.4pre3.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5764934/smartTemplate-fx-3.4pre3.zip)

**Comment by RealRaven2000** [comment]
And another improved version - fixing the vertical alignment of the labels + buttons:

[smartTemplate-fx-3.4pre4.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5764955/smartTemplate-fx-3.4pre4.zip)

**Comment by macdeport** [comment]
> Not quite sure what I am doing exactly here, but there is a trial version that seems to work maximizing the dropdown in Windows. Would be interesting to see whether it works on Mac, too:
> 
> smartTemplate-fx-3.4pre3.zip
👍  Mac, too

**Comment by RealRaven2000** [comment]
I am going to sneak this into the current release as 3.3.1 - since 3.3 wasn't reviewed yet this won't create extra work for the reviewers. Note: you won't be auto-updated when it drops as you have 3.4 installed (higher version number). So check near the end of the week and force install over or reinstall 3.2 to await the automatic update.

i got some bigger fish to fry for 3.4 but having a clear account selector is very important for new users.

**Comment by macdeport** [comment]
> [In addition, storing/restoring the last size and position of this window would be really useful for complex configurations/testing associated with these multiple identities.](https://github.com/RealRaven2000/SmartTemplate4/issues/110#issue-777723583)

What about this?

**Comment by RealRaven2000** [comment]
> > [In addition, storing/restoring the last size and position of this window would be really useful for complex configurations/testing associated with these multiple identities.](https://github.com/RealRaven2000/SmartTemplate4/issues/110#issue-777723583)
> 
> What about this?

this is separate. I think I had done it before but it's difficult with a flexible window now. Didn't find it super practical - I think center on screen or center on Thundebird might be better. Also, do not add this as "subfeature" with #110; it's not possible to track many changes in a single issue, because it means issues will never be finished.

**Comment by RealRaven2000** [comment]
implemented in 3.3.1 - released and reviewed on atn today
