### ISSUE TITLE
When FORWARDING, `%quotePlaceholder%` doesn't position forwarded mail text correctly

### ISSUE THREAD

**Issue by mbeeby** [RealRaven2000/SmartTemplate4#156]
The following template doesn't work as I understand it should:

`<b>This text comes before the quotePlaceholder</b>
%quotePlaceholder% %cursor%
<b>This text comes after the quotePlaceholder</b>`

Result, however, shows quoted text AFTER "**This text comes after the quotePlaceholder**":

![image](https://user-images.githubusercontent.com/8440136/137310532-fd95b81d-1290-402c-9634-e9581a9f3277.png)

**Comment by RealRaven2000** [comment]
I found the cause of the problem - apparently there is no special code of treating the forwarded mail "as a quote". Since there is no `<blockquote>` element nothing can be found to be moved into the position of the `%quotePlaceholder%` variable.

Original code from smartTemplate-compose.js:
```javascript
  let quotePart = bodyEl.querySelector("blockquote[_moz_dirty]");
  if (quotePart) {
    .. process quoted portion...
```
Patched code:
```javascript
    let quotePart = (st4composeType=='fwd') ?
	bodyEl.querySelector(".moz-forward-container") :
        bodyEl.querySelector("blockquote[_moz_dirty]");
    if (quotePart) {
```

Patched version to try out:
[smartTemplate-fx-3.8pre169.zip](https://github.com/RealRaven2000/SmartTemplates/files/7345784/smartTemplate-fx-3.8pre169.zip)

To try out this version, download the zip file and then drag said zip file into Thunderbird Add-ons Manager (do not unpack files).
