### ISSUE TITLE
Feature request: set variables from addressbook fields

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/SmartTemplate4#25]
SmartTemplate4 already reads and use the addressbook fields %firstname% & %name% from a given email address.

It could be nice other addressbook fields can be read in the same way.

**Comment by RealRaven2000** [comment]
Not sure why you closed this item (twice)? I am reopening it from here to start the discussion.

Ok, so let's start by adding some new field switches for the %from%, %to% %cc% and %bcc% variables; from the Edit Contact pages we could potentially extract:

Contact
---
nickname
additionalmail
chatname

Private
---
city
address1
address2
state
country
zipcode

at the moment these items are just concatenated with space, like this:

`%to(firstname,lastname,chatname,city,state,country)%` 

This would result in something like this:

John Smith @JoeSmith123 Toronto Canada

leaving out the missing parts. It might be helpful to be able to add a delimiter (ideally html) so be able to make a vertical list (maybe even a table). Maybe, by adding this as (optional) literal last parameter it may be more useful, something like this:

`%to(address1,address2,city,state,country,zipcode,"<br>")%`

the "<br>" would then be pre-pended to any non-empty value instead of a space character. empty values would just be ignored.

**Comment by macdeport** [comment]
"Not sure why you closed this item (twice)?" just a neophyte's false move ;-)

**Comment by macdeport** [comment]
Philosophy:

If the user spends time feeding the AB, it is likely to contain relevant information that can be used to enrich a response to the recipient(s).

A minimum (or a little more) of ST4 "conditional" such as [[...]] should allow you to take advantage of the information in the address book or, on the contrary, to manage its absence.

**Comment by RealRaven2000** [comment]
> A minimum (or a little more) of ST4 "conditional" such as [[...]] should allow you to take advantage of the information in the address book or, on the contrary, to manage its absence.
Yes, but that one is working through a really bad hack, so I don't like using that syntax. Normally the text replacement/insertion functions are programmed to not insert anything if they do not find any information.

At the moment AB lookup is only employed when the option "resolve names from address book" is activated. It means it will override whatever the user has give in his address line and use what you have in your AB for the name / firstname / lastname parameters.

**Comment by macdeport** [comment]
Thanks pointing out a more generic already existing mechanism for conditional replacement/insertion.

So variables of names such %ABfield_name% (if implemented), combined with text replacement/insertion functions, would make a great job.

**Comment by RealRaven2000** [comment]
> Thanks pointing out a more generic already existing mechanism for conditional replacement/insertion.
> 
> So variables of names such %ABfield_name% (if implemented), combined with text replacement/insertion functions, would make a great job.

not quite. The Adressbook item is derived using the email address using one of the standard headers,
%to(variables)%

**Comment by macdeport** [comment]
I am specially interested by **Other** fields:
_Custom 1_..._Custom 4_ (for special actions if implemented)
and the generic _Notes_

![floating-screenshot-204556](https://user-images.githubusercontent.com/26068595/70469061-9ee7e380-1ac8-11ea-83de-c9ee232b0d70.jpg)

For example, the next you reply to this recipient you can display automatically the remainder stored in his _Notes_

**Comment by RealRaven2000** [comment]
> 
> 
> I am specially interested by **Other** fields:
> _Custom 1_..._Custom 4_ (for special actions if implemented)
> and the generic _Notes_
> For example, the next time you reply to this recipient you can display automatically the remainder stored in his _Notes_

sure let's expand; I see there is alkso an address field in work, so let me expand the variables, like this:

Contact
---

nickname
additionalmail
chatname

Private
---

private.city
private.address1
private.address2
private.state
private.country
private.zipcode
private.webpage

Other
---

other.custom1
other.custom2
other.custom3
other.custom4
other.notes

Work
---

work.title
work.organization
work.address1
work.address2
work.city
work.state
work.zipcode
work.webpage

**Comment by RealRaven2000** [comment]
Still work in progress - I am leaving for Germany for the next 10 days; going to bring the laptop, maybe going to release a trial version here when I get some programming time in between. It appears that some AB fields are still not working, most likely just naming issues...

**Comment by RealRaven2000** [comment]
Implemented in v 27 - released on 09/01/2020
