### ISSUE TITLE
Support for TB version 60.9

### ISSUE THREAD

**Issue by hello-world-dot-c** [RealRaven2000/SmartTemplate4#306]
Long-time user of ST Pro here. Renewal is coming up and I noticed that I am still stuck at version 2.16.

Running the old TB version 60.9 is mandatory for me since I can't find a replacement for the theme I am using that works for me.

When did ST drop support for TB 60.9?

**Comment by RealRaven2000** [comment]
hello we didn't drop support, but we do not Backport all new code and functionality to old versions? if that's what you mean. what is the problem? 

Iirc Thunderbird has a different install script from version 78 ( they moved from install.rdf to manifest in order to support web extensions) this was already a fundamental change.

the complete localisation was ported from dtd and properties files to json also. then they started to rewrite a lot of backend code.  we had big changes due to this in Tb 91 and Tb 115. Tb 115 rewrote the complete UI  so I had to rewrite all buttons and menus. on top of that Modern Add-ons need to communicate with the App via a background script where it is allowed using the extensions API ( M which didn't exist back in the day of Tb60 or it was just in its infancy).

I had spent 1500$ on my own money to help with porting my Addons to v78 back in 2021 so that's basically a big cut off point for backportting functionality. 

the big front end changes of Tb115 last year also required to create a completely new code branch (called ESR115) which I can luckily keep using for the new version Thunderbird 128 which was published on July 11th.

if you prefer staying on Tb 60.8 and this works for it may be fine, it's just not possible to give you all the latest functionality as it is not feasible to rewrote all the code for outdated platforms.

**Comment by RealRaven2000** [comment]
PS: I am currently out of office so I have written the answer on my cellphone which sometimes leads to wrong word "corrections"; I tried my best to fix them after posting but you will only see my edits if you click on the link to visit Github as email alerts do not notify of such updates. 

thank you for your understanding.

**Comment by hello-world-dot-c** [comment]
So, is version 2.16 from three years ago the last one that works under TB 60.9?

I am asking because while it works "ok" it is far from perfect, there are a lot of quirks that were never resolved and where at some point I didn't want to bother support anymore. My hope was that perhaps a later version would have resolved some of them but if that's not an option then I may need to consider using something else.

I understand that it's a very tall order to keep supporting such a broad variety of targets but my main incentive to pay for the add-on back then was that (for a while) you kept support for "my" version going.

**Comment by RealRaven2000** [comment]
It is documented on the legacy change log:
https://smarttemplates.quickfolders.org/version-90.html
which deals with releases before Thunderbird 91. there is a section titled “Thunderbird 68 and older”.

maybe the problem isn’t that SmartTemplates doesn’t develop code for old versions but that your Theme stopped supporting modern versions of Thunderbird. What is it called? There may be a version for Tb 78 so you could at least move forward that far.

Note that security fixes in Thunderbird are only backported for one year either, and thats by a company that is supported by 20 million users (and funded accordingly)

just rewriting the SmartTemplates settings screen (issue #259) took me 6 weeks as a single developer. The Addon is indeed a different beast from the 2020 version.

**Comment by RealRaven2000** [comment]
Please check these pages
https://github.com/RealRaven2000/SmartTemplates/releases?page=9

**Comment by RealRaven2000** [comment]
Addons.thunderbird.net (then hosted by addons.mozilla.org) stopped accepting addon versions for thunderbird before 68, so i released quite a few maintenance patches here on Github under tagged releases. Check the ones where the version number starts with 2, you might get lucky. Its a little hard to chekc compatibility from here as i am on a bus at the moment…

**Comment by RealRaven2000** [comment]
Just checked, the next version was 2.17, see here:

https://github.com/RealRaven2000/SmartTemplates/releases/tag/2.17

this one requires Thunderbird 68, because it uses manifest.json instead of config.rdf and a bunch of other fundamental changes to the architecture… i did a bunch of backporting for 68 as i did parallel releases for ESR74 (starting with SmartTemplates Version nos 3.*) and 68 starting with 2.* but your Thunderbird is sadly too old for these….

**Comment by hello-world-dot-c** [comment]
Alright, thanks. My theme is Nautilus and version 60.9 of TB was the last one to support it fully.

**Comment by RealRaven2000** [comment]
> Alright, thanks. My theme is Nautilus and version 60.9 of TB was the last one to support it fully.

do you mean Nautipolis?

https://addons.thunderbird.net/de/seamonkey/addon/nautipolis-for-seamonkey/

**Comment by hello-world-dot-c** [comment]
> > Alright, thanks. My theme is Nautilus and version 60.9 of TB was the last one to support it fully.
> 
> do you mean Nautipolis?
> 
> https://addons.thunderbird.net/de/seamonkey/addon/nautipolis-for-seamonkey/

That's the one! 😄
