### ISSUE TITLE
Bug: ST4 with HTML Templates does not integrate in Reply/Forward buttons

### ISSUE THREAD

**Issue by RainerBoettchers** [RealRaven2000/SmartTemplate4#88]
And also not in context menu. 

Windows 10, v2004, TB 78.4.0 (32-bit) EN

**Comment by RealRaven2000** [comment]
did you try the latest beta, https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre56 ?

**Comment by RealRaven2000** [comment]
> And also not in context menu.
> 

That would be a new functionality - SmartTemplate never added anything to the "reply" context menus - if that's what you mean. It would mean a lot of clutter and potentially more bugs. So adding templates to the context menu would be a new feature reqest - please don't piggyback new function requests on top of bug issues. As regards the "meat" of this issued - did you test out [prerelease 56](https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre56)?

**Comment by RainerBoettchers** [comment]
Hello,

yes, I tried prerelase 56 and it works now as in
the ealier versions, to reply or forward with HTML
templates via the buttons in TB. It was not a
feature request but one feature of the previous version.
So it is solved.

Thanks,

Rainer

**Comment by adnanbatara** [comment]
Both prerelease 56 & 57 do not work with HTML templates in Thunderbird for Macos

**Comment by RealRaven2000** [comment]
ok, I am closing this issue for now.

**Comment by RealRaven2000** [comment]
> Both prerelease 56 & 57 do not work with HTML templates of Reply/Reply All/Forward operations in Thunderbird for Macos

Can you elaborate on "do not work" - are the menus not shown? Or are they not doing anything? "do not work" is always my favorite description, it leaves me completely in the dark as to what is happening. Didn't see your reply when I closed the issue.

**Comment by adnanbatara** [comment]
It only works with New message/Compose new message where its HTML template appears. When replying to/all or forwarding existing message, their HTML templates do not appear. 

I have just downgraded my Thunderbird to version 68 and SmartTemplate4 is working normally.

**Comment by RealRaven2000** [comment]
> It only works with New message/Compose new message where its HTML template appears. When replying to/all or forwarding existing message, their HTML templates do not appear.

Again "works" where? in the main toolbar:
![image](https://user-images.githubusercontent.com/6314674/97863862-96f7ea00-1cff-11eb-96a4-1acdb0729834.png)

Or in the header bar (above the mail preview):
![image](https://user-images.githubusercontent.com/6314674/97863956-bd1d8a00-1cff-11eb-8811-9ddae8fbb03a.png)

Are you using any other plugins that mess with the appearance / functionality of the header toolbar?

**Comment by adnanbatara** [comment]
HTML template only gets deployed in the body of Write New Message 
![image](https://user-images.githubusercontent.com/51467252/97865227-78641400-1d3c-11eb-830f-353e7d27626c.png)
but not in Reply/Reply All/Forward Message - Please see below screenshots
![image](https://user-images.githubusercontent.com/51467252/97865241-7e59f500-1d3c-11eb-84d5-06fa9e09078f.png)

**Comment by RealRaven2000** [comment]
> HTML template only gets deployed in the body of Write New Message
> 
> but not in Reply/Reply All/Forward Message - Please see below screenshots

Are you using external (HTML templates), which are selected from a dropdown (and which this issue is about) or the account specific ones? You know that if you have account specific templates you need to set one for each of the cases (Write / Reply / Forward)

![image](https://user-images.githubusercontent.com/6314674/97870257-a3357480-1d0a-11eb-8561-796fa375faba.png)

To activate the Reply templates you need to 
1) select the account  / identity
2) select the reply tab
3) Apply the template checkbox
4) Enter something in the template box.

Alternatively you can set up external templates using the dropdown attached to the "reply" button and click on "configure..."
![image](https://user-images.githubusercontent.com/6314674/97870531-ff989400-1d0a-11eb-8ddf-81c62d4750f3.png)

If you use external HTML templates from the dropdown, then the account one will automatically be ignored. Sending a screenshot of your composer doesn't really help me much as I do not know what you have configured. You can export your account specific template set (for write / reply and forward in a single file)
![image](https://user-images.githubusercontent.com/6314674/97874603-21951500-1d11-11eb-8f24-bee1ccff3fde.png)
(this will also include setting for quote header, html etc.) Note that this will not export your external list of html templates.

**Comment by RealRaven2000** [comment]
> HTML template only gets deployed in the body of Write New Message
> 
> but not in Reply/Reply All/Forward Message - Please see below screenshots

@adnanbatara - I think you refer to single message windows? I only fixed them in prerelease 69

https://github.com/RealRaven2000/SmartTemplate4/releases/tag/3.0pre69

**Comment by adnanbatara** [comment]
@RealRaven2000 yes, you are right. OK and noted where I am going to upgrade my Thunderbird for Macos version, deploy and test 3.0pre69. Thanks and I will revert afterward.

**Comment by RealRaven2000** [comment]
> @RealRaven2000 yes, you are right. OK and noted where I am going to upgrade my Thunderbird for Macos version, deploy and test 3.0pre69. Thanks and I will revert afterward.

or you can install the official version - I released yesterday and it was just reviewed this morning:
https://addons.thunderbird.net/en-US/thunderbird/addon/smarttemplate4/

**Comment by RealRaven2000** [comment]
This was fixed with the official release of 3.0 for Thunderbird 78
